'''8. Fazer um programa que imprime uma tabela com a tabuada de todas
as operações (soma, subtração, multiplicação e divisão) de 1 a 9.'''
n = int(input('Digite o valor do número: '))
print ('\n')
#Soma
print ('{} + {} = {}'.format(n, 1, n+1))
print ('{} + {} = {}'.format(n, 1, n+2))
print ('{} + {} = {}'.format(n, 1, n+3))
print ('{} + {} = {}'.format(n, 1, n+4))
print ('{} + {} = {}'.format(n, 1, n+5))
print ('{} + {} = {}'.format(n, 1, n+7))
print ('{} + {} = {}'.format(n, 1, n+8))
print ('{} + {} = {}'.format(n, 1, n+9))
#subtração
print ('\n')
print ('{} - {} = {}.'.format(n, 1, n-1))
print ('{} - {} = {}'.format(n, 1, n-2))
print ('{} - {} = {}'.format(n, 1, n-3))
print ('{} - {} = {}'.format(n, 1, n-4))
print ('{} - {} = {}'.format(n, 1, n-3))
print ('{} - {} = {}'.format(n, 1, n-4))
print ('{} - {} = {}'.format(n, 1, n-5))
print ('{} - {} = {}'.format(n, 1, n-6))
print ('{} - {} = {}'.format(n, 1, n-7))
print ('{} - {} = {}'.format(n, 1, n-8))
print ('{} - {} = {}'.format(n, 1, n-9))
#multiplicação
print ('\n')
print ('{} * {} = {}'.format(n, 1, n*1))
print ('{} * {} = {}'.format(n, 1, n*2))
print ('{} * {} = {}'.format(n, 1, n*3))
print ('{} * {} = {}'.format(n, 1, n*4))
print ('{} * {} = {}'.format(n, 1, n*5))
print ('{} * {} = {}'.format(n, 1, n*6))
print ('{} * {} = {}'.format(n, 1, n*7))
print ('{} * {} = {}'.format(n, 1, n*8))
print ('{} * {} = {}'.format(n, 1, n*9))
#divisão
print ('\n')
print ('{} / {} = {}'.format(n, 1, n/1))
print ('{} / {} = {}'.format(n, 1, n/2))
print ('{} / {} = {}'.format(n, 1, n/3))
print ('{} / {} = {}'.format(n, 1, n/4))
print ('{} / {} = {}'.format(n, 1, n/5))
print ('{} / {} = {}'.format(n, 1, n/6))
print ('{} / {} = {}'.format(n, 1, n/7))
print ('{} / {} = {}'.format(n, 1, n/8))
print ('{} / {} = {}'.format(n, 1, n/9))